apiVersion: v2
name: bear-helm
description: BEAR Helm chart for Kubernetes

type: application

version: 0.0.0

appVersion: "0.1.0"

dependencies:
- name: postgresql
  version: "11.9.13"
  repository: "https://charts.bitnami.com/bitnami"