backendReplicaCount: 1
enablePlayground: "true"
gemini_api_key: "placeholder"
openai_api_key: "placeholder"
api_key_hash: "placeholder"
aiType: "OPENAI"
clearlyDefinedApiUri: ""
useDefaultPostgrePass: true
create_secret_in_chart: "regular"
sealed_secrets_scope: "namespace-wide"

image:
  backEndImage: registry.relizahub.com/library/bear-backend:latest
  postgresImage: registry.relizahub.com/library/rearm-postgres:0.1.2@sha256:1d2b05e8662eb69bea12a04e91520e7f364e1ee3696a8a9feb0251c14b0f5950
  flywayImage: docker.io/redgate/flyway:11.14.0-alpine@sha256:19a1178e519f9c4448956bb7a7d7c52610e6c46503a5f752d13f04120092c45d
  pullPolicy: IfNotPresent

imagePullSecrets: [ {"name":"regcred"} ]

projectProtocol: http

traefik_crd_api_version: traefik.io/v1alpha1

useTraefikLe: true
traefikBehindLb: false
leHost: bear.localhost

backendService:
  type: ClusterIP
  port: 8085

postgresql:
  image:
    registry: registry.relizahub.com
    repository: library/rearm-postgres
    tag: 0.1.2
    digest: "@sha256:1d2b05e8662eb69bea12a04e91520e7f364e1ee3696a8a9feb0251c14b0f5950"
    pullPolicy: IfNotPresent
    pullSecrets: []
    debug: false
  auth:
    enablePostgresUser: true
    postgresPassword: relizaPass # change for prod use
  persistence:
    size: 30Gi
  primary:
    resourcesPreset: "medium"
    resources:
      requests:
        memory: "300Mi"
        cpu: "10m"
      limits:
        memory: "4000Mi"
        cpu: "4000m"