{{- if eq .Values.create_secret_in_chart "regular"}}
apiVersion: v1
kind: Secret
metadata:
  name: bear-api-key
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  BEAR_GEMINI_API_KEY: {{ .Values.gemini_api_key | b64enc | quote }}
  BEAR_OPENAI_API_KEY: {{ .Values.openai_api_key | b64enc | quote }}
---
{{- else if eq .Values.create_secret_in_chart "sealed"}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bear-api-key
  namespace: {{ .Values.namespace_override | default .Release.Namespace }}
  {{- if eq .Values.sealed_secrets_scope "namespace-wide"}}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  {{- else if eq .Values.sealed_secrets_scope "cluster-wide"}}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  {{- end }}
spec:
  encryptedData:
    BEAR_GEMINI_API_KEY: {{ .Values.gemini_api_key | quote }}
    BEAR_OPENAI_API_KEY: {{ .Values.openai_api_key | quote }}
---
{{- end}}

{{- if .Values.useDefaultPostgrePass}}
apiVersion: v1
kind: Secret
metadata:
  name: pgpassword
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  postgresql-password: {{ "relizaPass" | b64enc | quote }}
{{- end}}