on: [push]

name: Build Component Container Images And Submit Metadata To Reliza Hub

jobs:
  build-bear-backend:
    permissions:
      contents: read
      id-token: write
    name: Build And Push BEAR Backend
    runs-on: ubuntu-latest
    steps:
      - name: Build And Submit BEAR Backend Release to ReARM
        uses: relizaio/rearm-docker-action@a2d6978bea42cc6d707515bb927f0c693427fe58 # v1.10.0
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.relizahub.com
          image_namespace: registry.relizahub.com/library
          image_name: bear-backend
          rearm_api_id: ${{ secrets.RELIZA_BEAR_BACKEND_API_ID }}
          rearm_api_key: ${{ secrets.RELIZA_BEAR_BACKEND_API_KEY }}
          rearm_api_url: https://reliza.rearmhq.com
          path: backend
          enable_sbom: true
          source_code_sbom_type: npm
          enable_public_cosign_sigstore: true
  build-bear-helm:
    permissions:
      contents: write
      id-token: write
    name: Build And Push BEAR Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Build And Submit BEAR Helm Chart to ReARM
        uses: relizaio/rearm-helm-action@670ae40fd77b1892194ca8f4ffb7d86a403ef52e # v1.7.2
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.relizahub.com/library
          helm_chart_name: bear
          rearm_api_id: ${{ secrets.RELIZA_BEAR_HELM_API_ID }}
          rearm_api_key: ${{ secrets.RELIZA_BEAR_HELM_API_KEY }}
          rearm_api_url: https://reliza.rearmhq.com
          path: deploy/helm/bear-helm
          enable_sbom: true
          enable_public_cosign_sigstore: true
